name: 'Percy'

on: push

jobs:
  percy-deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Build CSS stylesheet
        run: npm run build-scss-storybook
      - name: Publish to Percy
        run: npx @percy/cli snapshot src/
